mozilla-services/amo2kinto

- kinto2xml/importer.py
- kinto2xml/tests/test_importer.py
- schemas.json
> Fix schema validation on production data

- kinto2xml/compare.py
- kinto2xml/exporter.py
- kinto2xml/tests/test_compare.py
- kinto2xml/tests/test_exporter.py
- kinto2xml/tests/test_verifier.py
- kinto2xml/verifier.py
> Add xml v2 support

- kinto2xml/constants.py
> Import into addons instead of add-ons (fixes #13)

- CHANGELOG.rst
- MANIFEST.in
- requirements.txt
- setup.py
**Step 1**
```
$ git co -b prepare-X.X
$ prerelease
$ git push origin prepare-X.X
```
**Step 2**
```
$ git co master
$ git merge --no-ff prepare-X.X
$ release
$ postrelease
```
**Step 3**
> Preparing release 0.1.0

- Makefile
- README.rst
- amo2kinto/constants.py
- amo2kinto/importer.py
- amo2kinto/tests/test_importer.py
- setup.py
- tox.ini
> Add documentation about json2kinto, kinto2xml and xml-verifier commands.

- amo2kinto/importer.py
- amo2kinto/tests/test_importer.py
> Display a warning if server doesn't supports schema validation. Refs #9

- amo2kinto/tests/test_verifier.py
- amo2kinto/verifier.py
> Make sure we return an error code in case the validation fails.

- CHANGELOG.rst
- setup.py
- tox.ini
> Preparing release 1.1.0

- CHANGELOG.rst
- README.rst
- amo2kinto/exporter.py
- amo2kinto/tests/test_exporter.py
- tox.ini
> Groub by guid when exporting the XML.

- CHANGELOG.rst
- setup.py
> Preparing release 1.2.0

- .coveragerc
- amo2kinto/importer.py
- amo2kinto/synchronize.py
- amo2kinto/tests/test_importer.py
- amo2kinto/tests/test_synchronize.py
> Add a way to update existing records that changed.

- CHANGELOG.rst
- setup.py
> Preparing release 1.3.0

- CHANGELOG.rst
- amo2kinto/exporter.py
- amo2kinto/importer.py
- amo2kinto/tests/test_exporter.py
- amo2kinto/tests/test_importer.py
> Add partial gfx versionRange handling

- CHANGELOG.rst
- setup.py
> Preparing release 1.4.0

- .gitignore
- CHANGELOG.rst
- MANIFEST.in
- README.rst
- amo2kinto/constants.py
- amo2kinto/exporter.py
- amo2kinto/generator.py
- amo2kinto/importer.py
- amo2kinto/templates/base.tpl
- amo2kinto/templates/collection.tpl
- amo2kinto/templates/record.tpl
- amo2kinto/tests/test_exporter.py
- amo2kinto/tests/test_generator.py
- amo2kinto/tests/test_importer.py
- requirements.txt
- setup.py
- tox.ini
> Add kinto blocked pages generator

- CHANGELOG.rst
- setup.py
> Preparing release 1.5.0

- CHANGELOG.rst
- setup.py
> Preparing release 1.5.1

- CHANGELOG.rst
- README.rst
- setup.py
> Preparing release 1.6.0

- CHANGELOG.rst
- amo2kinto/kinto.py
- amo2kinto/tests/test_kinto.py
> Allow json2kinto to work even without the bucket_creation permission.

- Makefile
> Makefile improvments.

- amo2kinto/templates/record.tpl
> Remove redundant footer

- amo2kinto/tests/test_verifier.py
- amo2kinto/verifier.py
@Natim wouldn't this help receive less alerts?
> Retry download of XML

- CHANGELOG.rst
- setup.py
> Preparing release 1.7.0

- amo2kinto/synchronize.py
> Strip schema keys from records

- CHANGELOG.rst
- amo2kinto/synchronize.py
- amo2kinto/tests/test_synchronize.py
> Use PUT instead of PATCH

- CHANGELOG.rst
- setup.py
> Preparing release 1.7.1

- CHANGELOG.rst
- MANIFEST.in
- Makefile
- amo2kinto/kinto.py
- amo2kinto/tests/test_kinto.py
>  Removed code in charge of updating the collection schema (#85) 

- CHANGELOG.rst
- amo2kinto/exporter.py
- amo2kinto/tests/test_exporter.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1473194
> Fix the XML item ID when squashing entries by addon ID
